apiVersion: v1
kind: Pod
metadata:
  name: multi-pod
spec:
  restartPolicy: Always
  containers:
    - name: sleepy-container
      image: jhansen/k8s-debugger:latest
      imagePullPolicy: Always
      command: [ "/bin/bash", "-c", "sleep 9000"]
    - name: outputter
      image: jhansen/k8s-debugger:latest
      imagePullPolicy: Always
      command: [ "/bin/bash", "-c", "while true; do echo 'hello'; sleep 1; done"]
