apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: left
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: label-show
        group: left
    spec:
      nodeSelector:
        name: larry
      containers:
      - name: nginx
        image: nginx:1.10.0
        ports:
        - containerPort: 80
