apiVersion: v1
kind: Service
metadata:
  name: right
  labels:
    app: nginx
    group: right
spec:
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: label-show
    group: right
